apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thanak81-uideveloper
  namespace: argocd
  annotations:
    notifications.argocd.argoproj.io/subscribe.on-sync-succeeded: "updateDeploymentStatusTrigger"
    notifications.argoproj.io/subscribe.on-sync-succeeded.telegram: "-1002195638358"
    notifications.argoproj.io/subscribe.on-sync-failed.telegram: "-1002195638358"
    notifications.argoproj.io/subscribe.on-deleted.telegram: "-1002195638358"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/LynaSovann/thanak81-uideveloper.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: thanak81-uideveloper
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 5
